#include <CL/cl.h>
#include <glib.h>

char *getPlatformName(cl_platform_id platform);
char *getPlatformProfile(cl_platform_id platform);
char *getPlatformVendor(cl_platform_id platform);
char *getPlatformVersion(cl_platform_id platform);
char *versionToStr(cl_uint version);
cl_name_version *getPlatformExtensions(cl_platform_id platform, size_t *);
cl_platform_id *getPlatforms(cl_uint *numPlatforms);
cl_ulong getPlatformHostTimerResolution(cl_platform_id platform);
cl_device_id *getDeviceIDs(cl_platform_id platform, cl_uint *numDevices);
GArray *getDeviceTypes(cl_device_id device);
cl_uint getDeviceVendorID(cl_device_id device);
cl_uint getDeviceMaxComputeUnits(cl_device_id device);
cl_uint getDeviceMaxWorkItemDimensions(cl_device_id device);
cl_uint getPreferredVectorWidthChar(cl_device_id device);
cl_uint getPreferredVectorWidthShort(cl_device_id device);
cl_uint getPreferredVectorWidthInt(cl_device_id device);
cl_uint getPreferredVectorWidthLong(cl_device_id device);
cl_uint getPreferredVectorWidthFloat(cl_device_id device);
cl_uint getPreferredVectorWidthDouble(cl_device_id device);
cl_uint getNativeVectorWidthChar(cl_device_id device);
cl_uint getNativeVectorWidthShort(cl_device_id device);
cl_uint getNativeVectorWidthInt(cl_device_id device);
cl_uint getNativeVectorWidthLong(cl_device_id device);
cl_uint getNativeVectorWidthFloat(cl_device_id device);
cl_uint getNativeVectorWidthDouble(cl_device_id device);
cl_uint getNativeVectorWidthHalf(cl_device_id device);
cl_uint getMaxClockFrequency(cl_device_id device);
cl_uint getAddressBits(cl_device_id device);
cl_uint getMaxReadImageArgs(cl_device_id device);
cl_uint getMaxWriteImageArgs(cl_device_id device);
cl_uint getMaxReadWriteImageArgs(cl_device_id device);
cl_uint getMaxSamplers(cl_device_id device);
cl_uint getImagePitchAlignment(cl_device_id device);
cl_uint getImageBaseAddressAlignment(cl_device_id device);
cl_uint getMaxPipeArgs(cl_device_id device);
cl_uint getPipeMaxActiveReservations(cl_device_id device);
cl_uint getPipeMaxPacketSize(cl_device_id device);
cl_uint getMemBaseAddrAlign(cl_device_id device);
cl_uint getGlobalMemCachelineSize(cl_device_id device);
cl_uint getMaxConstantArgs(cl_device_id device);
cl_uint getQueueOnDevicePreferredSize(cl_device_id device);
cl_uint getQueueOnDeviceMaxSize(cl_device_id device);
cl_uint getMaxOnDeviceQueues(cl_device_id device);
cl_uint getMaxOnDeviceEvents(cl_device_id device);
cl_uint getPartitionMaxSubDevices(cl_device_id device);
cl_uint getReferenceCount(cl_device_id device);
cl_uint getPreferredPlatformAtomicAlignment(cl_device_id device);
cl_uint getPreferredGlobalAtomicAlignment(cl_device_id device);
cl_uint getPreferredLocalAtomicAlignment(cl_device_id device);
cl_uint getMaxNumSubGroups(cl_device_id device);
